name: Build and Push Docker, Update Manifest

on:
workflow_dispatch:   
  push:
    branches: [ main ]

env:
  IMAGE_NAME: yuni0952/springboot-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.vars.outputs.TAG }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: vars
        run: |
          TAG="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: manifest
      - name: Update image tag in deployment.yaml
        run: |
          TAG=${{ needs.build-and-push.outputs.TAG }}
          IMG=${{ env.IMAGE_NAME }}
          sed -i "s#^\(\s*image:\s*\).*#\1${IMG}:${TAG}#g" k8s/deployment.yaml
          cat k8s/deployment.yaml
      - name: Commit and push
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${TAG:-${{ needs.build-and-push.outputs.TAG }}}" || echo "No changes"
          git push origin manifest
